baseurl = "https://www.tonimenzel.de/"
title = "Toni Menzel"
author = "Toni Menzel"
canonifyurls = true
languagecode = "de"

theme = "black-and-light-toni"

pygmentsstyle       = "bw"
pygmentscodefences  = true
relativeURLs = true
enableGitInfo = true

[params]
  sitename = "Toni Menzel"
  sitesubname = "Spiel auf Augenh√∂he"

  disableWebFonts = false
  logo="/tm_logo.png"

